### ISSUE TITLE
Adding category causes crash of application

### ISSUE THREAD

**Issue by Katarzyna-Kadziolka** [Katarzyna-Kadziolka/Athena#118]

**Comment by Morasiu** [comment]
Na początku aplikacji dodaj dane do `DbSet<Categories>`. 

Protip: Zerknij na App.cs i tam jest `EnsureDatabaseCreated`

Propozycja podania dania:
- zrób metodę w klasie `ApplicationDbContext` o nazwie `Seed()`
- Ma ona za zadania wypełnić bazę danych kategoriami
- Wywołaj ją po `EnsureDatabaseCreated`

Potem wydaj nową wersję z numerkiem `1.0.1`

**Comment by Morasiu** [comment]
Fixed in https://github.com/MossPiglets/Athena/pull/119
